spring:
  kafka:
    consumer:
      group-id: notification-group
      listener:
        missing-topics-fatal: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: my_email@gmail.com
    password: nyanyanya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

