server:
  port: 8082

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    consumer:
      group-id: notification-group
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: my_email@gmail.com
    password: nyanyanya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

topic:
  user-events: user-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka